In [1]:
## Run the cell below to attempt to programmatically find your crime file
import os,glob

## Getting the home folder from environment variables
home_folder = os.environ['HOME']
# print("- Your Home Folder is: " + home_folder)

## Check for downloads folder
if 'Downloads' in os.listdir(home_folder):
    
    
    # Print the Downloads folder path
    dl_folder = os.path.abspath(os.path.join(home_folder,'Downloads'))
    print(f"- Your Downloads folder is '{dl_folder}/'\n")
    
    ## checking for crime files using glob
    crime_files = sorted(glob.glob(dl_folder+'/**/Crimes_-_2001_to_Present*',recursive=True))
    
    # If more than 
    if len(crime_files)==1:
        RAW_FILE = crime_files[0]
        
    elif len(crime_files)>1:
        print('[i] The following files were found:')
        
        for i, fname in enumerate(crime_files):
            print(f"\tcrime_files[{i}] = '{fname}'")
        print(f'\n- Please fill in the RAW_FILE variable in the code cell below with the correct filepath.')

else:
    print(f'[!] Could not programmatically find your downloads folder.')
    print('- Try using Finder (on Mac) or File Explorer (Windows) to navigate to your Downloads folder.')

- Your Downloads folder is 'C:\Users\josep\Downloads/'

In [7]:
## (Required) MAKE SURE TO CHANGE THIS VARIABLE TO MATCH YOUR LOCAL FILE NAME
RAW_FILE = r"C:\Users\josep\Downloads\Crimes_-_2001_to_Present.csv"

if RAW_FILE == r"C:\Users\josep\Downloads\Crimes_-_2001_to_Present.csv":
	raise Exception("You must update the RAW_FILE variable to match your local filepath.")
	
RAW_FILE

Exception: You must update the RAW_FILE variable to match your local filepath.

In [9]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

In [10]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format',lambda x: f"{x:,.2f}")

In [11]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.00,12.00,61.00,08B,"1,165,074.00","1,875,917.00",2015,02/10/2018 03:50:01 PM,41.82,-87.67,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.00,29.00,25.00,06,"1,138,875.00","1,904,869.00",2015,02/10/2018 03:50:01 PM,41.90,-87.77,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631,6.00,8.00,44.00,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.00,35.00,21.00,18,"1,152,037.00","1,920,384.00",2015,02/10/2018 03:50:01 PM,41.94,-87.72,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.00,28.00,25.00,08A,"1,141,706.00","1,900,086.00",2015,02/10/2018 03:50:01 PM,41.88,-87.76,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786681,12847575,JF420478,09/01/2022 05:00:00 AM,005XX W SURF ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,1934,19.00,44.00,6.00,26,"1,172,497.00","1,919,410.00",2022,01/03/2023 03:46:28 PM,41.93,-87.64,"(41.934304581, -87.641484982)"
7786682,12847801,JF420319,07/08/2022 12:00:00 AM,114XX S PRAIRIE AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,STREET,False,False,531,5.00,9.00,49.00,11,"1,179,966.00","1,828,818.00",2022,01/03/2023 03:46:28 PM,41.69,-87.62,"(41.685543881, -87.616812541)"
7786683,12847324,JF420102,09/27/2022 11:00:00 AM,023XX E 70TH ST,0810,THEFT,OVER $500,RESIDENCE,False,False,331,3.00,5.00,43.00,06,"1,193,181.00","1,859,005.00",2022,01/03/2023 03:46:28 PM,41.77,-87.57,"(41.768068052, -87.567452932)"
7786684,12847570,JF420427,09/03/2022 10:25:00 AM,052XX W CARMEN AVE,2021,NARCOTICS,POSSESS - BARBITURATES,RESIDENCE - YARD (FRONT / BACK),True,False,1623,16.00,45.00,11.00,18,"1,140,553.00","1,933,418.00",2022,01/03/2023 03:46:28 PM,41.97,-87.76,"(41.973391184, -87.758534512)"
7786685,12840464,JF411839,09/26/2022 07:20:00 PM,0000X N MASON AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,False,1513,15.00,29.00,25.00,15,"1,136,773.00","1,899,652.00",2022,01/03/2023 03:46:28 PM,41.88,-87.77,"(41.880802263, -87.773245737)"

In [12]:
# explicitly setting the format to speed up pd.to_datetime
date_format = "%m/%d/%Y %H:%M:%S %p"


### Demonstrating/testing date_format
example = chicago_full.loc[0,'Date']
display(example)
pd.to_datetime(example,format=date_format)

'09/05/2015 01:30:00 PM'

Timestamp('2015-09-05 01:30:00')

In [13]:
# this cell can take up to 1 min to run
chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full = chicago_full.set_index('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Datetime,,,,,,,,,,,,,,,,,,,,,,
2001-01-01 01:00:00,1311358,G001819,01/01/2001 01:00:00 PM,025XX W 45 PL,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,914,9.00,NaN,NaN,05,"1,160,341.00","1,874,463.00",2001,08/17/2015 03:03:40 PM,41.81,-87.69,"(41.811226273, -87.687401084)"
2001-01-01 01:00:00,1315458,G005079,01/01/2001 01:00:00 AM,016XX N HUMBOLDT BL,0820,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,NaN,06,"1,156,090.00","1,910,543.00",2001,08/17/2015 03:03:40 PM,41.91,-87.70,"(41.910320325, -87.702020443)"
2001-01-01 01:00:00,1330412,G026686,01/01/2001 01:00:00 AM,019XX N HALSTED ST,0820,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,NaN,06,"1,170,604.00","1,913,228.00",2001,08/17/2015 03:03:40 PM,41.92,-87.65,"(41.917382588, -87.648623098)"
2001-01-01 01:00:00,1328315,G020979,01/01/2001 01:00:00 AM,067XX S JUSTINE ST,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,725,7.00,NaN,NaN,11,"1,167,126.00","1,859,954.00",2001,08/17/2015 03:03:40 PM,41.77,-87.66,"(41.771269195, -87.662929135)"
2001-01-01 01:00:00,1312658,G004147,01/01/2001 01:00:00 AM,040XX W CORTLAND ST,0460,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,NaN,08B,"1,149,393.00","1,912,364.00",2001,08/17/2015 03:03:40 PM,41.92,-87.73,"(41.915449949, -87.726575474)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-24 12:50:00,13053353,JG235640,04/24/2023 12:50:00 AM,039XX W 59TH ST,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,822,8.00,23.00,65.00,14,"1,151,153.00","1,865,190.00",2023,05/01/2023 04:47:24 PM,41.79,-87.72,"(41.785964352, -87.721344507)"
2023-04-24 12:52:00,13052241,JG235487,04/24/2023 12:52:00 PM,079XX S COTTAGE GROVE AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,624,6.00,6.00,44.00,08B,"1,182,930.00","1,852,635.00",2023,05/01/2023 04:47:24 PM,41.75,-87.61,"(41.750832464, -87.605224746)"
2023-04-24 12:53:00,13052266,JG235507,04/24/2023 12:53:00 PM,049XX S DREXEL BLVD,1812,NARCOTICS,POSSESS - CANNABIS MORE THAN 30 GRAMS,STREET,True,False,222,2.00,4.00,39.00,18,"1,183,148.00","1,872,501.00",2023,05/01/2023 04:47:24 PM,41.81,-87.60,"(41.805341531, -87.603808314)"
2023-04-24 12:55:00,13051811,JG234978,04/24/2023 12:55:00 AM,056XX N KIMBALL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,1711,17.00,39.00,13.00,08B,"1,152,697.00","1,937,247.00",2023,05/01/2023 04:47:24 PM,41.98,-87.71,"(41.983665907, -87.713775969)"
2023-04-24 12:59:00,13052580,JG235965,04/24/2023 12:59:00 PM,025XX E 96TH ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,True,431,4.00,7.00,51.00,11,"1,194,508.00","1,841,610.00",2023,05/01/2023 04:47:24 PM,41.72,-87.56,"(41.720302211, -87.563159628)"

In [14]:
(chicago_full.isna().sum()/len(chicago_full)).round(2)

ID                     0.00
Case Number            0.00
Date                   0.00
Block                  0.00
IUCR                   0.00
Primary Type           0.00
Description            0.00
Location Description   0.00
Arrest                 0.00
Domestic               0.00
Beat                   0.00
District               0.00
Ward                   0.08
Community Area         0.08
FBI Code               0.00
X Coordinate           0.01
Y Coordinate           0.01
Year                   0.00
Updated On             0.00
Latitude               0.01
Longitude              0.01
Location               0.01
dtype: float64

In [15]:
# save the years for every crime
chicago_full["Year"] = chicago_full.index.year
chicago_full["Year"] = chicago_full["Year"].astype(str)
chicago_full["Year"].value_counts()

2002    486804
2001    485879
2003    475980
2004    469421
2005    453771
2006    448174
2007    437084
2008    427167
2009    392819
2010    370496
2011    351964
2012    336262
2013    307468
2014    275731
2016    269786
2017    269073
2018    268773
2015    264755
2019    261248
2022    238240
2020    212098
2021    208575
2023     75118
Name: Year, dtype: int64

In [16]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [17]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols).sort_index()#.reset_index()
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,1311358,01/01/2001 01:00:00 PM,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,914,9.00,NaN,2001,41.81,-87.69
2001-01-01 01:00:00,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,2001,41.91,-87.70
2001-01-01 01:00:00,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,2001,41.92,-87.65
2001-01-01 01:00:00,1328315,01/01/2001 01:00:00 AM,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,725,7.00,NaN,2001,41.77,-87.66
2001-01-01 01:00:00,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,2001,41.92,-87.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-24 12:50:00,13053353,04/24/2023 12:50:00 AM,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,822,8.00,23.00,2023,41.79,-87.72
2023-04-24 12:52:00,13052241,04/24/2023 12:52:00 PM,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,624,6.00,6.00,2023,41.75,-87.61
2023-04-24 12:53:00,13052266,04/24/2023 12:53:00 PM,NARCOTICS,POSSESS - CANNABIS MORE THAN 30 GRAMS,STREET,True,False,222,2.00,4.00,2023,41.81,-87.60
2023-04-24 12:55:00,13051811,04/24/2023 12:55:00 AM,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,1711,17.00,39.00,2023,41.98,-87.71
2023-04-24 12:59:00,13052580,04/24/2023 12:59:00 PM,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,True,431,4.00,7.00,2023,41.72,-87.56

In [18]:
chicago_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7786686 entries, 2001-01-01 01:00:00 to 2023-04-24 12:59:00
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Date                  object
 2   Primary Type          object
 3   Description           object
 4   Location Description  object
 5   Arrest                bool
 6   Domestic              bool
 7   Beat                  int64
 8   District              float64
 9   Ward                  float64
 10  Year                  object
 11  Latitude              float64
 12  Longitude             float64
dtypes: bool(2), float64(4), int64(2), object(5)
memory usage: 727.7+ MB

In [19]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
      dtype=object)

In [20]:
FINAL_DROP = ['Datetime','Year']#,'Location Description']

In [21]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[ year]
    temp_df = temp_df.reset_index(drop=False)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}Chicago-Crime_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

[i] Saving .csv's to Data/Chicago/

In [22]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['Data/Chicago\\Chicago-Crime_2001.csv',
 'Data/Chicago\\Chicago-Crime_2002.csv',
 'Data/Chicago\\Chicago-Crime_2003.csv',
 'Data/Chicago\\Chicago-Crime_2004.csv',
 'Data/Chicago\\Chicago-Crime_2005.csv',
 'Data/Chicago\\Chicago-Crime_2006.csv',
 'Data/Chicago\\Chicago-Crime_2007.csv',
 'Data/Chicago\\Chicago-Crime_2008.csv',
 'Data/Chicago\\Chicago-Crime_2009.csv',
 'Data/Chicago\\Chicago-Crime_2010.csv',
 'Data/Chicago\\Chicago-Crime_2011.csv',
 'Data/Chicago\\Chicago-Crime_2012.csv',
 'Data/Chicago\\Chicago-Crime_2013.csv',
 'Data/Chicago\\Chicago-Crime_2014.csv',
 'Data/Chicago\\Chicago-Crime_2015.csv',
 'Data/Chicago\\Chicago-Crime_2016.csv',
 'Data/Chicago\\Chicago-Crime_2017.csv',
 'Data/Chicago\\Chicago-Crime_2018.csv',
 'Data/Chicago\\Chicago-Crime_2019.csv',
 'Data/Chicago\\Chicago-Crime_2020.csv',
 'Data/Chicago\\Chicago-Crime_2021.csv',
 'Data/Chicago\\Chicago-Crime_2022.csv',
 'Data/Chicago\\Chicago-Crime_2023.csv']

In [23]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

In [24]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f) for f in crime_files])
df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude
0,1311358,01/01/2001 01:00:00 PM,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,914,9.00,NaN,41.81,-87.69
1,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,41.91,-87.70
2,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,41.92,-87.65
3,1328315,01/01/2001 01:00:00 AM,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,725,7.00,NaN,41.77,-87.66
4,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,41.92,-87.73
...,...,...,...,...,...,...,...,...,...,...,...,...
75113,13053353,04/24/2023 12:50:00 AM,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,822,8.00,23.00,41.79,-87.72
75114,13052241,04/24/2023 12:52:00 PM,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,624,6.00,6.00,41.75,-87.61
75115,13052266,04/24/2023 12:53:00 PM,NARCOTICS,POSSESS - CANNABIS MORE THAN 30 GRAMS,STREET,True,False,222,2.00,4.00,41.81,-87.60
75116,13051811,04/24/2023 12:55:00 AM,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,1711,17.00,39.00,41.98,-87.71
75117,13052580,04/24/2023 12:59:00 PM,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,True,431,4.00,7.00,41.72,-87.56

In [25]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

2001    485879
2002    486804
2003    475980
2004    469421
2005    453771
2006    448174
2007    437084
2008    427167
2009    392819
2010    370496
2011    351964
2012    336262
2013    307468
2014    275731
2015    264755
2016    269786
2017    269073
2018    268773
2019    261248
2020    212098
2021    208575
2022    238240
2023     75118
Name: Date, dtype: int64